# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf5eb6243304020035dbd855f1319fd89ec49ea1d19abd8e295c8e3e3712e7c8d878e220eb3b7a3c5a325113f923dabcdb8999f0171d78525bd5b05fe6b77586

test:
  secret_key_base: 116e2b26f4c4e2b6cb5ca61d8248ff8dda1933b1cc6df3ec73ce9afc3d204170d74896884b52e511bccb07f6bf75a739506d2684e4789f0921619007e2e610d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
